# Ayu Dark
$bg0     = rgb(0b0e14)
$bg1     = rgb(131721)
$bg2     = rgb(1a1f2b)
$bg3     = rgb(1e2430)
$bg4     = rgb(272d3b)

$fg      = rgb(bfbdb6)
$accent  = rgb(53bdfa)

$red     = rgb(ea6c73)
$orange  = rgb(f9af4f)
$yellow  = rgb(f9af4f)
$green   = rgb(7fd962)
$aqua    = rgb(90e1c6)
$blue    = rgb(53bdfa)
$purple  = rgb(cda1fa)

$grey0   = rgb(928374)
$grey1   = rgb(a89984)
$grey2   = rgb(bdae93)