$bg0   = rgb(1D1F27)
$bg1   = rgb(16181e)
$bg2   = rgb(282b36)
$bg3   = rgb(2f3340)
$bg4   = rgb(393d4d)

$fg     = rgb(D5D8DA)

$red    = rgb(E95678)
$orange = rgb(F09383)
$yellow = rgb(FAC29A)
$green  = rgb(27D796)
$aqua   = rgb(21BFC2)
$blue   = rgb(75BEFF)
$purple = rgb(B877DB)

$grey0 = rgb(4f546b)
$grey1 = rgb(5b607b)
$grey2 = rgb(757b99)