# Nightfox
$bg0     = rgb(192330)
$bg1     = rgb(212e3d)
$bg2     = rgb(29394a)
$bg3     = rgb(2b3b51)
$bg4     = rgb(39495e)

$fg      = rgb(cdcecf)
$accent =   rgb(719cd6)

$red     = rgb(c94f6d)
$orange  = rgb(f4a261)
$yellow  = rgb(dbc074)
$green   = rgb(81b29a)
$aqua    = rgb(63cdcf)
$blue    = rgb(719cd6)
$purple  = rgb(9d79d6)

$grey0   = rgb(393b44)
$grey1   = rgb(575860)
$grey2   = rgb(71717a)