# Rose Pine
$bg0     = rgb(1f1d2e)
$bg1     = rgb(2a2837)
$bg2     = rgb(353243)
$bg3     = rgb(403d4f)
$bg4     = rgb(4b485a)

$fg      = rgb(e0def4)
$accent  = rgb(9ccfd8)

$red     = rgb(eb6f92)
$orange  = rgb(f6c177)
$yellow  = rgb(f6c177)
$green   = rgb(31748f)
$aqua    = rgb(ebbcba)
$blue    = rgb(9ccfd8)
$purple  = rgb(c4a7e7)

$grey0   = rgb(2f2c40)
$grey1   = rgb(908caa)
$grey2   = rgb(6e6a86)