$bg0    =  rgb(061115)
$bg1    =  rgb(0d181c)
$bg2    =  rgb(131e22)
$bg3    =  rgb(1c272b)
$bg4    =  rgb(242f33)

$fg     =  rgb(D9D7D6)
$accent =  rgb(6791C9)

$red    =  rgb(DF5B61)
$orange =  rgb(E89982)
$yellow =  rgb(ecd28b)
$green  =  rgb(78B892)
$aqua   =  rgb(67AFC1)
$blue   =  rgb(6791C9)
$purple =  rgb(C488EC)

$grey0 =  rgb(313c40)
$grey1 =  rgb(3b464a)
$grey2 =  rgb(4f5a5e)