$bg0    =   rgb(1a1b26)
$bg1    =   rgb(24283b)
$bg2    =   rgb(2f3549)
$bg3    =   rgb(3b4261)
$bg4    =   rgb(545c7e)

$fg     =   rgb(c0caf5)
$accent =   rgb(7aa2f7)

$red    =   rgb(f7768e)
$orange =   rgb(ff9e64)
$yellow =   rgb(e0af68)
$green  =   rgb(9ece6a)
$aqua   =   rgb(73daca)
$blue   =   rgb(7aa2f7)
$purple =   rgb(bb9af7)

$grey0  =   rgb(414868)
$grey1  =   rgb(565f89)
$grey2  =   rgb(a9b1d6)