local M = {}

$bg0     = rgb(101010)
$bg1     = rgb(1c1c1c)
$bg2     = rgb(232323)
$bg3     = rgb(282828)
$bg4     = rgb(343434)

$fg      = rgb(ffffff)
$accent  = rgb(ffc799)

$red     = rgb(ff8080)
$orange  = rgb(ffc799)
$yellow  = rgb(ffc799)
$green   = rgb(99ffe4)
$aqua    = rgb(99ffe4)
$blue    = rgb(99c9ff)
$purple  = rgb(fbadff)

$grey0   = rgb(505050)
$grey1   = rgb(595959)
$grey2   = rgb(7e7e7e)

