# Colors
source = $HOME/.config/hypr/colors/colors.conf


# Sources
source = $HOME/.config/hypr/modules/Monitors.conf 
source = $HOME/.config/hypr/modules/Programs.conf
source = $HOME/.config/hypr/modules/Autostart.conf
source = $HOME/.config/hypr/modules/Env.conf
source = $HOME/.config/hypr/modules/Windowrules.conf
source = $HOME/.config/hypr/modules/Layerrules.conf
source = $HOME/.config/hypr/modules/Layout.conf
source = $HOME/.config/hypr/modules/Misc.conf
source = $HOME/.config/hypr/modules/Inpute.conf
source = $HOME/.config/hypr/modules/Keybinds.conf
source = $HOME/.config/hypr/modules/Permission.conf

# Customizable Sources 
source = $HOME/.config/hypr/modules/Animations.conf
source = $HOME/.config/hypr/modules/Decoration.conf
