# Waybar
layerrule = match:namespace waybar, blur on
#layerrule = match:namespace waybar, ignorezero
layerrule = match:namespace waybar, ignore_alpha 0.5
layerrule = match:namespace waybar, no_anim on

# Swaync
layerrule = match:namespace swaync-control-center, blur on
layerrule = match:namespace swaync-notification-window, blur on

layerrule = match:namespace swaync-control-center, ignore_alpha 0.5
layerrule = match:namespace swaync-notification-window, ignore_alpha 0.5

layertrule = match:namespace notification-popups, animation fade

# Wlogout
layerrule = match:namespace logout_dialog, animation fade
layerrule = match:namespace logout_dialog, blur on


# Rofi
layerrule = match:namespace rofi, animation popin 80%
#layerrule = match:namespace rofi, blur on
#layerrule = match:namespace rofi, ignorezero 
#layerrule = match:namespace rofi, ignore_alpha 0.5 

# Rofi App Drawer
#layerrule[appdrawer-blur] {
#    match:namespace = appdrawer
#    blur = true
#    ignore_alpha = 0.5
#    animation = popin 80%
#}