#/*-----Apps-----*/#
$terminal = kitty
$fileManager = nautilus # gsettings set org.gnome.desktop.wm.preferences button-layout ":" (Use This in Terminal to hide Close icons)
$browser = helium-browser
$editor = code

