windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}

# Ignore maximize requests
#windowrulev2 = suppressevent maximize, class:.*

# Remove the weird pop-up behavior in VSCode
#windowrulev2 = stayfocused, class:^(codium)$
#windowrule = minsize 1 1, class:^(codium)$

#windowrule { 
#  match:class = ^(polkit-gnome-authentication-agent-1)$ 
#  float = on
#}

# Make file picker windows floating
windowrule {
    name = file-picker
    match:title = ^(Open File|Open Folder|Open|Save|Save As|Export|Choose File|Rename|script-fu)$
    float = on
    center = on
    size = 600 300
} 

windowrule {
    name = xdg-desktop-portal-gtk
    match:class =  xdg-desktop-portal-gtk
    float = on
    center = on
    size = 800 500
} 

windowrule {
    name = xdg-desktop-portal-hyprland
    match:class = xdg-desktop-portal-hyprland
    float = on
    center = on
    size = 900 600
} 

# Float All Dailog Window
windowrule = match:modal true, float on
windowrule = match:modal true, center on

# Float font switcher
windowrule {
    name = font-switcher
    match:title = ^Font Switcher$
    float = on
    center = on
    size = 400 200
} 

# Broweser
windowrule {
    name = browser
    match:class = ^(firefox|librewolf|brave|chromium|chromium-browser|microsoft-edge|zen|helium-browser)$,
    #workspace = 1 silent,
    no_blur = true
}

windowrule {
    name = Picture-in-Picture
    match:title = ^(Picture-in-Picture)$
    float = on
    pin = on
    no_initial_focus = on
    size = 540 300
    move = 850 450
    opacity = 1.0
}

# File Manager
windowrule {
    name = file-manager
    match:class = ^(org.gnome.Nautilus|thunar|dolphin)$
    #workspace = 3 silent
    float = on
    center = on
    size = 1100 600
    border_size = 0
} 

# Code Editor
windowrule {
    name = editor
    match:class = ^(code|codium)$
    #workspace = 2 silent
    border_size = 0
} 

# Note-taking
windowrule {
    name = note-taking
    match:class = ^(notion|notion-calendar|obsidian)$
    #workspace = 4 silent
}

# Music Player
windowrule {
    name = music-player
    match:class = ^(spotify)$
    #workspace = 5 silent
}

# Terminal
windowrule {
    name = terminal
    match:class = ^(kitty|ghoty|alacrity)$
    float = on
    center = on
    size = 950 500
} 


