animations {
    enabled = true

    # Curve definitions (The "Apple" feel)
    bezier = md3_decel, 0.05, 0.7, 0.1, 1
    bezier = overshot, 0.05, 0.9, 0.1, 1.05
    bezier = hyprcurve, 0.05, 0.9, 0.1, 1.1

    # Window Animations
    animation = windows, 1, 7, overshot, popin 80%
    animation = windowsIn, 1, 7, md3_decel, popin 80%
    animation = windowsOut, 1, 5, md3_decel, popin 80%
    animation = windowsMove, 1, 6, md3_decel, slide
    
    # Layer/UI Animations (Waybar, Wofi)
    animation = layers, 1, 4, md3_decel, slide top
    animation = fade, 1, 10, default, 
    
    # Workspace transitions (Smooth & snappy)
    animation = workspaces, 1, 6, md3_decel, slidefade 20%
}